version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CHAINCODE_NAME=chaincodetcc
      - CHANNEL_NAME=channeltcc
    volumes:
      - ./crypto:/crypto