version: '3.8'

services:
  besu-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: besu-gateway-service
    ports:
      - "8082:8082"
    environment:
      # Variáveis de ambiente para a aplicação
      #- PORT=8082
      - GIN_MODE=release
      
      # Variáveis de ambiente para Besu/Ethereum (opcionais - podem vir do arquivo de configuração)
      #- RPC_URL=http://host.docker.internal:8550
      #- CHAIN_ID=1337
      
      # Variáveis de ambiente para AWS (opcionais - podem ser sobrescritas)
      #- AWS_REGION=${AWS_REGION:-us-east-1}
      #- AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      #- AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      
    volumes:
      # Volumes para arquivos de configuração (permitindo edição externa)
      - ./CCInfra/DB/aws_config.yaml:/app/CCInfra/DB/aws_config.yaml:ro
      - ./CCInfra/RPC_besu/rpc_config.yaml:/app/CCInfra/RPC_besu/rpc_config.yaml:ro
      
      # Volume para logs (usando volume nomeado)
      - besu-logs:/app/logs
      
    networks:
      - besu-gateway-network
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  besu-gateway-network:
    driver: bridge
    name: besu-gateway-network

volumes:
  besu-logs:
    driver: local
  besu-data:
    driver: local