basePath: /
host: localhost:8081
info:
  contact: {}
  description: API para criar e consultar lotes de testes de qualidade usando Hyperledger
    Fabric.
  title: Quality Test API Hyperledger Fabric
  version: "1.0"
paths:
  /batch:
    post:
      consumes:
      - application/json
      description: Envia uma transação para criar um novo lote de teste de qualidade
        no Hyperledger Fabric.
      parameters:
      - description: Dados do lote de teste de qualidade
        in: body
        name: batch
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Lote de teste de qualidade criado com sucesso
          schema:
            type: string
        "500":
          description: Erro ao criar lote de teste de qualidade
          schema:
            type: string
      summary: Cria um novo lote de teste de qualidade
      tags:
      - batch
  /batch/{id}:
    get:
      consumes:
      - application/json
      description: Consulta os detalhes de um lote de teste de qualidade pelo ID.
      parameters:
      - description: ID do lote de teste
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Dados do lote de teste de qualidade
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Lote não encontrado
          schema:
            type: string
        "500":
          description: Erro ao consultar lote
          schema:
            type: string
      summary: Consulta um lote de teste de qualidade
      tags:
      - batch
swagger: "2.0"
