basePath: /
definitions:
  handler.CreateBatchRequest:
    properties:
      id:
        type: string
      maxLimit:
        type: integer
      minLimit:
        type: integer
      productionOrder:
        type: string
      testDate:
        type: string
      testDescription:
        type: string
      values:
        items:
          type: integer
        type: array
    type: object
host: localhost:8082
info:
  contact: {}
  description: API para criar e consultar lotes de testes de qualidade usando contratos
    Solidity.
  title: Quality Test API
  version: "1.0"
paths:
  /batch:
    post:
      consumes:
      - application/json
      description: Envia uma transação para criar um novo lote de testes de qualidade
        no contrato Solidity
      parameters:
      - description: Dados do lote
        in: body
        name: batch
        required: true
        schema:
          $ref: '#/definitions/handler.CreateBatchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Cria um novo lote de testes de qualidade
      tags:
      - Batch
  /batch/{id}:
    get:
      consumes:
      - application/json
      description: Faz uma consulta ao contrato Solidity para obter os detalhes de
        um lote pelo ID
      parameters:
      - description: ID do lote
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Consulta os detalhes de um lote de testes de qualidade
      tags:
      - Batch
  /ws/latest-block:
    get:
      description: Conecta ao nó Ethereum via WebSocket e notifica o cliente sempre
        que um novo bloco for minerado
      produces:
      - application/json
      responses:
        "101":
          description: Conexão WebSocket estabelecida
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Erro ao conectar ao nó Ethereum ou WebSocket
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Estabelece uma conexão WebSocket para receber o último bloco em tempo
        real
      tags:
      - Blockchain
swagger: "2.0"
